#!/bin/bash

ep /etc/php.ini
ep /etc/php-fpm.conf
ep /etc/php-fpm.d/*

[ ! -e /run/php-fpm ] && mkdir -p /run/php-fpm

if [ "$(ls -A /var/www/)" ]; then
    echo "Contenta already installed, please update manually if you need to."
else
    echo "Installing contenta"
    cd /usr/local/src

    php -r "readfile('https://raw.githubusercontent.com/contentacms/contenta_jsonapi_project/8.x-2.x/scripts/download.sh');" > download-contentacms.sh
    chmod a+x download-contentacms.sh
    ./download-contentacms.sh /var/www
fi

exec "$@"
